from __future__ import annotations

import copy
import itertools
import re
from dataclasses import dataclass
from typing import Any

from ktabforge.config.matrix import MatrixConfig
from ktabforge.utils.hashing import stable_hash

_SAFE_ID = re.compile(r"^[A-Za-z0-9_.-]+$")


@dataclass(frozen=True)
class ExpandedExperiment:
    experiment_id: str
    payload: dict[str, Any]
    axis_values: dict[str, Any]
    config_hash: str


@dataclass(frozen=True)
class MatrixPlan:
    factory_id: str
    competition: str
    runs: list[ExpandedExperiment]


def expand_matrix_config(config: MatrixConfig, *, max_runs: int | None = None) -> MatrixPlan:
    limit = max_runs if max_runs is not None else config.max_runs
    if limit is not None and limit <= 0:
        raise ValueError("max_runs must be greater than 0")
    runs: list[ExpandedExperiment] = []
    seen_ids: set[str] = set()

    for axis_values in _axis_product(config.axes):
        payload = copy.deepcopy(config.base_experiment)
        for dotted_path, value in axis_values.items():
            _set_dotted(payload, dotted_path, value)

        experiment_id = _render_template(config.experiment_id_template, payload)
        _validate_experiment_id(experiment_id)
        if experiment_id in seen_ids:
            raise ValueError(f"Duplicate experiment_id generated by matrix: {experiment_id}")
        seen_ids.add(experiment_id)

        experiment = payload.setdefault("experiment", {})
        if not isinstance(experiment, dict):
            raise TypeError("base_experiment.experiment must be a mapping.")
        experiment["experiment_id"] = experiment_id
        experiment["competition"] = config.competition
        _ensure_outputs(payload, config=config, experiment_id=experiment_id)

        runs.append(
            ExpandedExperiment(
                experiment_id=experiment_id,
                payload=payload,
                axis_values=dict(axis_values),
                config_hash=stable_hash(payload),
            )
        )

    limited_runs = runs[:limit] if limit is not None else runs
    return MatrixPlan(
        factory_id=config.factory_id,
        competition=config.competition,
        runs=limited_runs,
    )


def _axis_product(axes: dict[str, list[Any]]) -> list[dict[str, Any]]:
    keys = list(axes.keys())
    values = [axes[key] for key in keys]
    return [dict(zip(keys, item, strict=True)) for item in itertools.product(*values)]


def _set_dotted(payload: dict[str, Any], dotted_path: str, value: Any) -> None:
    parts = dotted_path.split(".")
    current: dict[str, Any] = payload
    for part in parts[:-1]:
        child = current.setdefault(part, {})
        if not isinstance(child, dict):
            raise TypeError(f"Cannot set {dotted_path!r}; {part!r} is not a mapping.")
        current = child
    current[parts[-1]] = value


def _get_dotted(payload: dict[str, Any], dotted_path: str) -> Any:
    current: Any = payload
    for part in dotted_path.split("."):
        if not isinstance(current, dict) or part not in current:
            raise KeyError(dotted_path)
        current = current[part]
    return current


def _render_template(template: str, payload: dict[str, Any]) -> str:
    result = template
    for match in re.findall(r"{([^{}]+)}", template):
        value = _get_dotted(payload, match)
        result = result.replace("{" + match + "}", str(value))
    return result


def _validate_experiment_id(experiment_id: str) -> None:
    if not experiment_id:
        raise ValueError("experiment_id must not be empty")
    if "/" in experiment_id or "\\" in experiment_id or ".." in experiment_id:
        raise ValueError(f"Unsafe experiment_id generated by matrix: {experiment_id}")
    if not _SAFE_ID.match(experiment_id):
        raise ValueError(f"Unsafe experiment_id generated by matrix: {experiment_id}")


def _ensure_outputs(
    payload: dict[str, Any],
    *,
    config: MatrixConfig,
    experiment_id: str,
) -> None:
    outputs = payload.setdefault("outputs", {})
    if not isinstance(outputs, dict):
        raise TypeError("base_experiment.outputs must be a mapping when provided.")
    data = payload.setdefault("data", {})
    if not isinstance(data, dict):
        raise TypeError("base_experiment.data must be a mapping.")
    data["artifact_root"] = str(config.artifact_root)
    root = str(config.artifact_root)
    competition = config.competition
    outputs["experiment_dir"] = f"{root}/experiments/{competition}/{experiment_id}"
    outputs["oof_dir"] = f"{root}/oof/{competition}/{experiment_id}"
    outputs["submission_dir"] = f"{root}/submissions/{competition}/{experiment_id}"
